### ISSUE TITLE
Initial installation and usage (terminus version compatibility)

### ISSUE THREAD

**Issue by nadavoid** [rvtraveller/terminus-composer#5]
I've installed this plugin and have tried it on a new, composer based Drupal 8 site on pantheon, but it exits quickly without any messages or errors. For example:

```
in ~
○ terminus composer
[2016-10-19 22:52:58] [error] usage: terminus composer <commands>... [--site=<site>] [--env=<environment>]

in ~
○ terminus composer "install" --site=mysite --env=dev

in ~
○
```

I can use terminus to execute drush commands, so I know I'm connecting successfully to the site. Also, I was able to use the [Pancakes Plugin](https://github.com/derimagia/terminus-pancakes).

I've also tried other composer commands like update, about, and help, but nothing seems to happen, even after adding a require in the site's composer.json file.

Any thoughts on other things I can check to successfully run this plugin?

**Comment by nadavoid** [comment]
ah hah! It has to do with terminus versions. I was using 0.13.3. This plugin does work with terminus 0.12.0. I tried updating to terminus' master branch, but things must be changing even more there. It complained that it couldn't find the "composer" command at all.

**Comment by rvtraveller** [comment]
@nadavoid can you try again now?  I just merged a PR to support Terminus 0.13.x.

**Comment by nadavoid** [comment]
@rvtraveller It seems like it's connecting and doing something now; it takes a couple of seconds to execute a "help" or "info" composer command. But I still don't see any output in the terminal. Tested using terminus 0.13.3

**Comment by rvtraveller** [comment]
Alright, in our ongoing battle to keep up with Terminus I just merged #7 which should (again) jumpstart this.  I'm successfully able to run composer commands against a site now.  Can you test again?

**Comment by nadavoid** [comment]
You got it! I just tested (still with terminus version 0.13.3) and I see all the expected terminal output now: switching to ftp, output of the composer command, switching back to git. Very nice! I'm looking forward to using this actively in the coming weeks.

Thank you very much for creating this plugin and updating it as terminus versions progress.
